=== YousefAdel2020/XML_labs/day2/task1/emp.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employees (employee)>
<!ELEMENT employee (name,phones,addresses,email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type CDATA #REQUIRED>
<!ELEMENT addresses (address)>
<!ELEMENT address (street,building_no,region,city,country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT building_no (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== YousefAdel2020/XML_labs/day2/task1/task 1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM 'emp.dtd'>
<employees>
	<employee>
		<name>Yousef</name>
		<phones>
			<phone type="home">05456046546</phone>
		</phones>
		<addresses>
			<address>
				<street>khalid abn el walid</street>
				<building_no>15</building_no>
				<region>sidi besher</region>
				<city>Alex</city>
				<country>Egypt</country>
			</address>
		</addresses>
		<email>Yousef@gmail.com</email>
	</employee>
	<employee>
		<name>Ali</name>
		<phones>
			<phone type="home">05456046546</phone>
		</phones>
		<addresses>
			<address>
				<street>khalid abn el walid</street>
				<building_no>15</building_no>
				<region>sidi besher</region>
				<city>Alex</city>
				<country>Egypt</country>
			</address>
		</addresses>
		<email>Ali@gmail.com</email>
	</employee>
</employees>
